- name: Stop existing EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Stop EC2 instance
      amazon.aws.ec2_instance:
        instance_ids:
          -  i-09***********58  # <-- your instance ID
        region: ap-south-2
        state: terminated
        wait: yes
